import '../models/product_model.dart';
import '../models/order_model.dart';
import '../models/user_model.dart';

class SeedData {
  static List<Product> get products => [
        Product(
          id: '1',
          name: 'AT Clutch Friction Plate 3.5mm',
          slug: 'at-clutch-friction-plate-3-5mm',
          sku: 'DT-CP-0001',
          category: 'clutch_plate',
          description:
              'High-performance automatic transmission clutch friction plate. 3.5mm thickness, OEM-equivalent material composition.',
          specifications: {
            'thickness': '3.5mm',
            'material': 'Organic Friction',
            'diameter': '165mm'
          },
          compatibleVehicles: ['Toyota Hilux', 'Toyota Fortuner', 'Isuzu D-Max'],
          compatibleGearboxes: ['A750E', 'A750F'],
          price: 28.00,
          costPrice: 15.00,
          wholesalePrice: 22.00,
          minWholesaleQty: 10,
          stockQty: 150,
          stockStatus: 'in_stock',
          lowStockThreshold: 20,
          tags: ['clutch', 'friction', 'a750e'],
          isFeatured: true,
          createdAt: DateTime(2026, 1, 15),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '2',
          name: 'HD Clutch Disc A750E',
          slug: 'hd-clutch-disc-a750e',
          sku: 'DT-CP-0002',
          category: 'clutch_plate',
          description:
              'Heavy-duty clutch disc designed for A750E transmissions. Enhanced friction material for towing.',
          specifications: {
            'thickness': '4.0mm',
            'material': 'Kevlar Blend',
            'diameter': '170mm'
          },
          compatibleVehicles: ['Toyota Land Cruiser', 'Lexus GX470'],
          compatibleGearboxes: ['A750E'],
          price: 35.00,
          costPrice: 18.00,
          wholesalePrice: 28.00,
          minWholesaleQty: 10,
          stockQty: 85,
          stockStatus: 'in_stock',
          lowStockThreshold: 15,
          createdAt: DateTime(2026, 1, 15),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '3',
          name: 'Steel Separator Plate 1.8mm',
          slug: 'steel-separator-plate-1-8mm',
          sku: 'DT-SP-0001',
          category: 'steel_plate',
          description:
              'Precision-ground steel separator plate for automatic transmissions.',
          specifications: {
            'thickness': '1.8mm',
            'material': 'Hardened Steel',
            'finish': 'Phosphate coated'
          },
          compatibleVehicles: ['Toyota Hilux', 'Mitsubishi Triton'],
          compatibleGearboxes: ['A750E', 'A340'],
          price: 16.00,
          costPrice: 8.00,
          wholesalePrice: 12.00,
          minWholesaleQty: 20,
          stockQty: 200,
          stockStatus: 'in_stock',
          lowStockThreshold: 30,
          createdAt: DateTime(2026, 1, 20),
          updatedAt: DateTime(2026, 3, 28),
        ),
        Product(
          id: '4',
          name: 'Waved Steel Plate A340',
          slug: 'waved-steel-plate-a340',
          sku: 'DT-SP-0002',
          category: 'steel_plate',
          description:
              'Waved steel plate for A340 series transmissions.',
          specifications: {
            'thickness': '2.0mm',
            'material': 'Spring Steel',
            'pattern': 'Waved'
          },
          compatibleVehicles: ['Toyota Hilux', 'Toyota 4Runner'],
          compatibleGearboxes: ['A340'],
          price: 20.00,
          costPrice: 10.00,
          wholesalePrice: 15.00,
          minWholesaleQty: 20,
          stockQty: 120,
          stockStatus: 'in_stock',
          lowStockThreshold: 20,
          createdAt: DateTime(2026, 1, 20),
          updatedAt: DateTime(2026, 3, 28),
        ),
        Product(
          id: '5',
          name: 'ATF Inline Filter Universal',
          slug: 'atf-inline-filter-universal',
          sku: 'DT-AF-0001',
          category: 'auto_filter',
          description:
              'Universal inline ATF filter for automatic transmissions.',
          specifications: {
            'type': 'Inline',
            'micron': '25μm',
            'connection': '3/8" barb'
          },
          compatibleVehicles: ['Universal'],
          compatibleGearboxes: ['Universal'],
          price: 12.00,
          costPrice: 5.00,
          wholesalePrice: 9.00,
          minWholesaleQty: 25,
          stockQty: 300,
          stockStatus: 'in_stock',
          lowStockThreshold: 50,
          isFeatured: true,
          createdAt: DateTime(2026, 2, 1),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '6',
          name: 'Pan Transmission Filter Kit',
          slug: 'pan-transmission-filter-kit',
          sku: 'DT-AF-0002',
          category: 'auto_filter',
          description: 'Complete pan filter kit with gasket.',
          specifications: {
            'type': 'Pan filter',
            'includes': 'Filter + gasket',
            'material': 'Felt/Metal mesh'
          },
          compatibleVehicles: ['Toyota Hilux', 'Toyota Fortuner'],
          compatibleGearboxes: ['A750E', 'A750F'],
          price: 25.00,
          costPrice: 12.00,
          wholesalePrice: 19.00,
          minWholesaleQty: 15,
          stockQty: 95,
          stockStatus: 'in_stock',
          lowStockThreshold: 15,
          createdAt: DateTime(2026, 2, 1),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '7',
          name: 'Forward Clutch Drum A750E',
          slug: 'forward-clutch-drum-a750e',
          sku: 'DT-FD-0001',
          category: 'forward_drum',
          description:
              'Complete forward clutch drum assembly for A750E transmissions.',
          specifications: {
            'material': 'Cast Aluminum',
            'bushing': 'Pre-installed',
            'splines': '36T'
          },
          compatibleVehicles: [
            'Toyota Hilux',
            'Toyota Fortuner',
            'Lexus GX470'
          ],
          compatibleGearboxes: ['A750E'],
          price: 120.00,
          costPrice: 65.00,
          wholesalePrice: 95.00,
          minWholesaleQty: 3,
          stockQty: 25,
          stockStatus: 'in_stock',
          lowStockThreshold: 5,
          isFeatured: true,
          createdAt: DateTime(2026, 2, 10),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '8',
          name: 'Forward Drum Shell Assembly',
          slug: 'forward-drum-shell-assembly',
          sku: 'DT-FD-0002',
          category: 'forward_drum',
          description: 'Replacement drum shell for various automatic transmissions.',
          specifications: {
            'material': 'Steel',
            'finish': 'Machined',
            'weight': '1.2kg'
          },
          compatibleVehicles: ['Toyota Hilux', 'Nissan Navara'],
          compatibleGearboxes: ['A340', 'RE5R05A'],
          price: 105.00,
          costPrice: 55.00,
          wholesalePrice: 85.00,
          minWholesaleQty: 3,
          stockQty: 18,
          stockStatus: 'in_stock',
          lowStockThreshold: 5,
          createdAt: DateTime(2026, 2, 10),
          updatedAt: DateTime(2026, 3, 20),
        ),
        Product(
          id: '9',
          name: 'Front Oil Pump Body A340',
          slug: 'front-oil-pump-body-a340',
          sku: 'DT-OP-0001',
          category: 'oil_pump',
          description:
              'Remanufactured front oil pump body for A340 transmissions.',
          specifications: {
            'type': 'Front pump body',
            'condition': 'Remanufactured',
            'seals': 'Included'
          },
          compatibleVehicles: ['Toyota Hilux', 'Toyota 4Runner'],
          compatibleGearboxes: ['A340'],
          price: 150.00,
          costPrice: 80.00,
          wholesalePrice: 120.00,
          minWholesaleQty: 2,
          stockQty: 15,
          stockStatus: 'in_stock',
          lowStockThreshold: 5,
          isFeatured: true,
          createdAt: DateTime(2026, 2, 15),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '10',
          name: 'Oil Pump Gear Set',
          slug: 'oil-pump-gear-set',
          sku: 'DT-OP-0002',
          category: 'oil_pump',
          description: 'Replacement inner and outer gear set for transmission oil pumps.',
          specifications: {
            'type': 'Gear set (inner + outer)',
            'material': 'Hardened Steel'
          },
          compatibleVehicles: ['Toyota Hilux', 'Mitsubishi Triton'],
          compatibleGearboxes: ['A750E', 'A340'],
          price: 85.00,
          costPrice: 45.00,
          wholesalePrice: 68.00,
          minWholesaleQty: 5,
          stockQty: 30,
          stockStatus: 'in_stock',
          lowStockThreshold: 8,
          createdAt: DateTime(2026, 2, 15),
          updatedAt: DateTime(2026, 3, 28),
        ),
        Product(
          id: '11',
          name: 'Bonded Piston Seal Kit A750E',
          slug: 'bonded-piston-seal-kit-a750e',
          sku: 'DT-PS-0001',
          category: 'piston_seal',
          description:
              'Complete bonded piston seal kit for A750E automatic transmissions.',
          specifications: {
            'pieces': '6 seals',
            'material': 'Viton rubber bonded to steel',
            'type': 'Bonded'
          },
          compatibleVehicles: [
            'Toyota Hilux',
            'Toyota Fortuner',
            'Lexus GX470'
          ],
          compatibleGearboxes: ['A750E'],
          price: 14.00,
          costPrice: 6.00,
          wholesalePrice: 10.00,
          minWholesaleQty: 20,
          stockQty: 250,
          stockStatus: 'in_stock',
          lowStockThreshold: 40,
          createdAt: DateTime(2026, 3, 1),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '12',
          name: 'D-Ring Seal Assortment',
          slug: 'd-ring-seal-assortment',
          sku: 'DT-PS-0002',
          category: 'piston_seal',
          description: 'Assorted D-ring seals for automatic transmission hydraulic circuits.',
          specifications: {
            'pieces': '24 assorted',
            'material': 'NBR rubber',
            'sizes': 'Mixed (12mm–45mm)'
          },
          compatibleVehicles: ['Universal'],
          compatibleGearboxes: ['Universal'],
          price: 10.00,
          costPrice: 4.00,
          wholesalePrice: 7.50,
          minWholesaleQty: 30,
          stockQty: 400,
          stockStatus: 'in_stock',
          lowStockThreshold: 60,
          createdAt: DateTime(2026, 3, 1),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '13',
          name: 'Master Rebuild Kit A750E',
          slug: 'master-rebuild-kit-a750e',
          sku: 'DT-OK-0001',
          category: 'overhaul_kit',
          description:
              'Complete master overhaul kit for A750E automatic transmissions.',
          specifications: {
            'includes': 'Frictions, steels, seals, gaskets, bushings',
            'coverage': 'Full overhaul'
          },
          compatibleVehicles: [
            'Toyota Hilux',
            'Toyota Fortuner',
            'Lexus GX470'
          ],
          compatibleGearboxes: ['A750E'],
          price: 250.00,
          costPrice: 120.00,
          wholesalePrice: 195.00,
          minWholesaleQty: 2,
          stockQty: 20,
          stockStatus: 'in_stock',
          lowStockThreshold: 5,
          isFeatured: true,
          createdAt: DateTime(2026, 3, 10),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '14',
          name: 'Banner Kit A340',
          slug: 'banner-kit-a340',
          sku: 'DT-OK-0002',
          category: 'overhaul_kit',
          description:
              'Gasket and seal kit (banner kit) for A340 transmissions.',
          specifications: {
            'includes': 'Gaskets, O-rings, lip seals, pan gasket',
            'coverage': 'Seals only'
          },
          compatibleVehicles: ['Toyota Hilux', 'Toyota 4Runner'],
          compatibleGearboxes: ['A340'],
          price: 160.00,
          costPrice: 80.00,
          wholesalePrice: 128.00,
          minWholesaleQty: 3,
          stockQty: 35,
          stockStatus: 'in_stock',
          lowStockThreshold: 8,
          createdAt: DateTime(2026, 3, 10),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '15',
          name: 'ATF Dexron VI 1L',
          slug: 'atf-dexron-vi-1l',
          sku: 'DT-LB-0001',
          category: 'lubricants',
          description:
              'Premium automatic transmission fluid meeting Dexron VI specifications.',
          specifications: {
            'volume': '1 Litre',
            'spec': 'Dexron VI',
            'type': 'Fully synthetic'
          },
          compatibleVehicles: ['Universal'],
          compatibleGearboxes: ['Universal'],
          price: 18.00,
          costPrice: 8.00,
          wholesalePrice: 14.00,
          minWholesaleQty: 20,
          stockQty: 500,
          stockStatus: 'in_stock',
          lowStockThreshold: 50,
          isFeatured: true,
          createdAt: DateTime(2026, 1, 5),
          updatedAt: DateTime(2026, 4, 1),
        ),
        Product(
          id: '16',
          name: 'CVT Fluid NS-3 1L',
          slug: 'cvt-fluid-ns3-1l',
          sku: 'DT-LB-0002',
          category: 'lubricants',
          description:
              'CVT-specific transmission fluid compatible with Nissan NS-3 specification.',
          specifications: {
            'volume': '1 Litre',
            'spec': 'NS-3 Compatible',
            'type': 'Fully synthetic'
          },
          compatibleVehicles: [
            'Nissan Navara',
            'Nissan X-Trail',
            'Mitsubishi Outlander'
          ],
          compatibleGearboxes: ['JF015E', 'JF011E'],
          price: 22.00,
          costPrice: 10.00,
          wholesalePrice: 17.00,
          minWholesaleQty: 20,
          stockQty: 350,
          stockStatus: 'in_stock',
          lowStockThreshold: 40,
          createdAt: DateTime(2026, 1, 5),
          updatedAt: DateTime(2026, 4, 1),
        ),
      ];

  static List<Order> get orders => [
        Order(
          id: 'ord-1',
          orderNumber: 'DT-260405-0001',
          items: [
            const OrderItem(
              productId: '1',
              productName: 'AT Clutch Friction Plate 3.5mm',
              sku: 'DT-CP-0001',
              quantity: 10,
              unitPrice: 22.00,
              total: 220.00,
            ),
            const OrderItem(
              productId: '3',
              productName: 'Steel Separator Plate 1.8mm',
              sku: 'DT-SP-0001',
              quantity: 20,
              unitPrice: 12.00,
              total: 240.00,
            ),
          ],
          shipping: const ShippingAddress(
            fullName: 'Ahmad Razak',
            company: 'Razak Gearbox Workshop',
            phone: '+60 12-345 6789',
            email: 'ahmad@razakgearbox.com',
            addressLine1: '12, Jalan Industri 3',
            city: 'Shah Alam',
            state: 'Selangor',
            postalCode: '40150',
          ),
          subtotal: 460.00,
          shippingCost: 15.00,
          total: 475.00,
          status: 'confirmed',
          paymentMethod: 'bank_transfer',
          paymentStatus: 'paid',
          createdAt: DateTime(2026, 4, 5, 9, 30),
          updatedAt: DateTime(2026, 4, 5, 14, 0),
        ),
        Order(
          id: 'ord-2',
          orderNumber: 'DT-260406-0001',
          items: [
            const OrderItem(
              productId: '13',
              productName: 'Master Rebuild Kit A750E',
              sku: 'DT-OK-0001',
              quantity: 1,
              unitPrice: 250.00,
              total: 250.00,
            ),
            const OrderItem(
              productId: '15',
              productName: 'ATF Dexron VI 1L',
              sku: 'DT-LB-0001',
              quantity: 4,
              unitPrice: 18.00,
              total: 72.00,
            ),
          ],
          shipping: const ShippingAddress(
            fullName: 'Lee Wei Ming',
            phone: '+60 16-789 0123',
            email: 'wm.lee@gmail.com',
            addressLine1: '88, Jalan Merdeka',
            city: 'Kuala Lumpur',
            state: 'W.P. Kuala Lumpur',
            postalCode: '50100',
          ),
          subtotal: 322.00,
          shippingCost: 15.00,
          total: 337.00,
          status: 'pending',
          paymentMethod: 'bank_transfer',
          paymentStatus: 'unpaid',
          createdAt: DateTime(2026, 4, 6, 11, 15),
          updatedAt: DateTime(2026, 4, 6, 11, 15),
        ),
        Order(
          id: 'ord-3',
          orderNumber: 'DT-260407-0001',
          items: [
            const OrderItem(
              productId: '7',
              productName: 'Forward Clutch Drum A750E',
              sku: 'DT-FD-0001',
              quantity: 2,
              unitPrice: 95.00,
              total: 190.00,
            ),
            const OrderItem(
              productId: '11',
              productName: 'Bonded Piston Seal Kit A750E',
              sku: 'DT-PS-0001',
              quantity: 20,
              unitPrice: 10.00,
              total: 200.00,
            ),
            const OrderItem(
              productId: '5',
              productName: 'ATF Inline Filter Universal',
              sku: 'DT-AF-0001',
              quantity: 10,
              unitPrice: 9.00,
              total: 90.00,
            ),
          ],
          shipping: const ShippingAddress(
            fullName: 'Muthu Samy',
            company: 'MSK Auto Parts Sdn Bhd',
            phone: '+60 19-456 7890',
            email: 'muthu@mskauto.com.my',
            addressLine1: '5, Lorong Perindustrian 7',
            addressLine2: 'Kawasan Perindustrian Puchong',
            city: 'Puchong',
            state: 'Selangor',
            postalCode: '47100',
          ),
          subtotal: 480.00,
          shippingCost: 15.00,
          total: 495.00,
          status: 'processing',
          paymentMethod: 'bank_transfer',
          paymentStatus: 'paid',
          createdAt: DateTime(2026, 4, 7, 8, 45),
          updatedAt: DateTime(2026, 4, 7, 16, 0),
        ),
        Order(
          id: 'ord-4',
          orderNumber: 'DT-260408-0001',
          items: [
            const OrderItem(
              productId: '9',
              productName: 'Front Oil Pump Body A340',
              sku: 'DT-OP-0001',
              quantity: 1,
              unitPrice: 150.00,
              total: 150.00,
            ),
          ],
          shipping: const ShippingAddress(
            fullName: 'Tan Ah Kow',
            phone: '+60 17-234 5678',
            email: 'tankow@outlook.com',
            addressLine1: '33, Jalan Bukit Bintang',
            city: 'Johor Bahru',
            state: 'Johor',
            postalCode: '80000',
          ),
          subtotal: 150.00,
          shippingCost: 15.00,
          total: 165.00,
          status: 'pending',
          paymentMethod: 'cod',
          paymentStatus: 'unpaid',
          createdAt: DateTime(2026, 4, 8, 7, 0),
          updatedAt: DateTime(2026, 4, 8, 7, 0),
        ),
        Order(
          id: 'ord-5',
          orderNumber: 'DT-260401-0001',
          items: [
            const OrderItem(
              productId: '15',
              productName: 'ATF Dexron VI 1L',
              sku: 'DT-LB-0001',
              quantity: 20,
              unitPrice: 14.00,
              total: 280.00,
            ),
            const OrderItem(
              productId: '16',
              productName: 'CVT Fluid NS-3 1L',
              sku: 'DT-LB-0002',
              quantity: 20,
              unitPrice: 17.00,
              total: 340.00,
            ),
          ],
          shipping: const ShippingAddress(
            fullName: 'Ahmad Razak',
            company: 'Razak Gearbox Workshop',
            phone: '+60 12-345 6789',
            email: 'ahmad@razakgearbox.com',
            addressLine1: '12, Jalan Industri 3',
            city: 'Shah Alam',
            state: 'Selangor',
            postalCode: '40150',
          ),
          subtotal: 620.00,
          shippingCost: 0,
          total: 620.00,
          status: 'delivered',
          paymentMethod: 'bank_transfer',
          paymentStatus: 'paid',
          createdAt: DateTime(2026, 4, 1, 10, 0),
          updatedAt: DateTime(2026, 4, 4, 14, 30),
        ),
      ];

  static List<AppUser> get customers => [
        AppUser(
          id: 'u-1',
          email: 'ahmad@razakgearbox.com',
          fullName: 'Ahmad Razak',
          phone: '+60 12-345 6789',
          company: 'Razak Gearbox Workshop',
          isTradeAccount: true,
          totalOrders: 12,
          totalSpent: 8450.00,
          createdAt: DateTime(2025, 8, 10),
        ),
        AppUser(
          id: 'u-2',
          email: 'wm.lee@gmail.com',
          fullName: 'Lee Wei Ming',
          phone: '+60 16-789 0123',
          totalOrders: 3,
          totalSpent: 892.00,
          createdAt: DateTime(2026, 1, 22),
        ),
        AppUser(
          id: 'u-3',
          email: 'muthu@mskauto.com.my',
          fullName: 'Muthu Samy',
          phone: '+60 19-456 7890',
          company: 'MSK Auto Parts Sdn Bhd',
          isTradeAccount: true,
          totalOrders: 8,
          totalSpent: 5640.00,
          createdAt: DateTime(2025, 11, 3),
        ),
        AppUser(
          id: 'u-4',
          email: 'tankow@outlook.com',
          fullName: 'Tan Ah Kow',
          phone: '+60 17-234 5678',
          totalOrders: 1,
          totalSpent: 165.00,
          createdAt: DateTime(2026, 4, 8),
        ),
        AppUser(
          id: 'u-5',
          email: 'fatimah@ymail.com',
          fullName: 'Fatimah Zahra',
          phone: '+60 13-567 8901',
          company: 'FZ Transmission Services',
          isTradeAccount: true,
          isVerified: false,
          totalOrders: 0,
          totalSpent: 0,
          createdAt: DateTime(2026, 4, 7),
        ),
      ];
}
